// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package usersdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	VerifyUser(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
